=== Trylobot/isoblox/user/iso_grid.dtd
<?xml version="1.0"?>
<!-- Project isoblox XML Document Type Definition -->
<!ELEMENT iso_grid (size,iso_block*)>
<!ATTLIST iso_grid name CDATA "Untitled">
<!ELEMENT size (EMPTY)>
<!ATTLIST size x CDATA "1">
<!ATTLIST size y CDATA "1">
<!ATTLIST size z CDATA "1">
<!ELEMENT iso_block (color,offset)>
<!ATTLIST iso_block isotype CDATA "0">
<!ELEMENT color (EMPTY)>
<!ATTLIST color r CDATA "255">
<!ATTLIST color g CDATA "255">
<!ATTLIST color b CDATA "255">
<!ELEMENT offset (EMPTY)>
<!ATTLIST offset x CDATA "0">
<!ATTLIST offset y CDATA "0">
<!ATTLIST offset z CDATA "0">

=== Trylobot/isoblox/user/pyramid.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE iso_grid SYSTEM "iso_grid.dtd">
<iso_grid name="pyramid">
	<size x="3" y="3" z="3"/>
	<iso_block isotype="0"><color r="255" g="210" b="210"/><offset x="2" y="0" z="0"/></iso_block>
	<iso_block isotype="0"><color r="210" g="255" b="210"/><offset x="0" y="2" z="0"/></iso_block>
	<iso_block isotype="0"><color r="210" g="210" b="255"/><offset x="0" y="0" z="2"/></iso_block>
	<iso_block isotype="0"><color r="232" g="232" b="210"/><offset x="1" y="1" z="0"/></iso_block>
	<iso_block isotype="0"><color r="232" g="210" b="232"/><offset x="1" y="0" z="1"/></iso_block>
	<iso_block isotype="0"><color r="210" g="232" b="232"/><offset x="0" y="1" z="1"/></iso_block>
</iso_grid>
